# Generated by Django 4.1.3 on 2022-12-12 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_catag_categ_alter_categ_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product'),
            preserve_default=False,
        ),
    ]
