# Generated by Django 4.1.3 on 2023-01-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdata',
            name='user',
        ),
    ]
